fix: grept apply

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -1,58 +1,71 @@
 ---
-  name: e2e test
-  
-  on:
-    pull_request:
-      types: ['opened', 'reopened', 'synchronize']
-    merge_group:
-    workflow_dispatch:
-  
-  permissions:
-    contents: read
-    id-token: write
-  
-  jobs:
-    getexamples:
-      runs-on: ubuntu-latest
-      outputs:
-        examples: ${{ steps.getexamples.outputs.examples }}
-      steps:
-        - uses: actions/checkout@v4
-        - name: get examples
-          id: getexamples
-          uses: Azure/terraform-azurerm-avm-template/.github/actions/e2e-getexamples@main
-          with:
-            github-token: ${{ secrets.GITHUB_TOKEN }}
-  
-    testexamples:
-      runs-on: ubuntu-latest
-      needs: getexamples
-      environment: test
-      env:
-        TF_IN_AUTOMATION: 1
-        TF_VAR_enable_telemetry: false
-      strategy:
-        matrix:
-          example: ${{ fromJson(needs.getexamples.outputs.examples) }}
-        max-parallel: 5
-      steps:
-        - uses: actions/checkout@v4
-  
-        - uses: Azure/login@v1
-          with:
-            client-id: ${{ secrets.AZURE_CLIENT_ID }}
-            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-  
-        - name: Test example
-          uses: Azure/terraform-azurerm-avm-template/.github/actions/e2e-testexamples@main
-          with:
-            example: ${{ matrix.example }}
-  
-    # This job is only run when all the previous jobs are successful.
-    # We can use it for PR validation to ensure all examples have completed.
-    testexamplescomplete:
-      runs-on: ubuntu-latest
-      needs: testexamples
-      steps:
-        - run: echo "All tests passed"
+name: e2e test
+
+on:
+  pull_request:
+    types: ['opened', 'reopened', 'synchronize']
+  merge_group:
+  workflow_dispatch:
+
+permissions:
+  contents: read
+  id-token: write
+
+jobs:
+  getexamples:
+    if: github.event.repository.name != 'terraform-azurerm-avm-template'
+    runs-on: ubuntu-latest
+    outputs:
+      examples: ${{ steps.getexamples.outputs.examples }}
+    steps:
+      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.1.2
+      - name: get examples
+        id: getexamples
+        uses: Azure/terraform-azurerm-avm-template/.github/actions/e2e-getexamples@main
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+
+  testexamples:
+    if: github.event.repository.name != 'terraform-azurerm-avm-template'
+    runs-on: [ self-hosted, 1ES.Pool=2964b8e1530b27b8f17ff522c8e9cadc9ebad01c ]
+    needs: getexamples
+    environment: test
+    env:
+      TF_IN_AUTOMATION: 1
+      TF_VAR_enable_telemetry: false
+    strategy:
+      matrix:
+        example: ${{ fromJson(needs.getexamples.outputs.examples) }}
+      fail-fast: false
+    steps:
+      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.1.2
+
+      - name: Test example
+        shell: bash
+        run: |
+          set -e
+           MAX_RETRIES=10
+          RETRY_COUNT=0
+          until [ $RETRY_COUNT -ge $MAX_RETRIES ]
+          do
+            az login --identity --username $MSI_ID > /dev/null && break
+            RETRY_COUNT=$[$RETRY_COUNT+1]
+            sleep 10
+          done
+          if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+            echo "Failed to login after $MAX_RETRIES attempts."
+            exit 1
+          fi
+          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
+          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
+          export ARM_CLIENT_ID=$(az identity list | jq -r --arg MSI_ID "$MSI_ID" '.[] | select(.principalId == $MSI_ID) | .clientId')
+          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src -w /src --network=host -e TF_IN_AUTOMATION -e TF_VAR_enable_telemetry -e AVM_MOD_PATH=/src -e AVM_EXAMPLE=${{ matrix.example }} -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_CLIENT_ID -e ARM_USE_MSI=true mcr.microsoft.com/azterraform:latest make test-example
+
+  # This job is only run when all the previous jobs are successful.
+  # We can use it for PR validation to ensure all examples have completed.
+  testexamplescomplete:
+    if: github.event.repository.name != 'terraform-azurerm-avm-template'
+    runs-on: ubuntu-latest
+    needs: testexamples
+    steps:
+      - run: echo "All tests passed"
